CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO (
	RA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50),
	ENDER VARCHAR(50),
	FONE VARCHAR(20)
);

CREATE TABLE DISCIPLINA (
	IDDISC INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50)
);

CREATE TABLE NOTA (
	RA INT NOT NULL ,
    IDDISC INT NOT NULL,
    PRIMARY KEY(RA, IDDISC),
    NOTA1 DOUBLE,
    NOTA2 DOUBLE,
    NOTA3 DOUBLE,
    FOREIGN KEY(RA) REFERENCES ALUNO(RA),
    FOREIGN KEY(IDDISC) REFERENCES DISCIPLINA(IDDISC)
);