SELECT 
	A.NOME AS ALUNO,
	D.NOME AS DISCIPLINA,
	N.NOTA1,
	N.NOTA2,
	N.NOTA3, 
    ROUND((N.NOTA1+N.NOTA2+N.NOTA3)/3)
FROM 
	ALUNO A,
	DISCIPLINA D,
	NOTA N 
WHERE N.RA = A.RA 
AND N.IDDISC = D.IDDISC